#!/bin/sh
set -e
# Debconf questions that depend on whether we edited boot config are asked from postinst.
if [ -f /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
    db_version 2.0
fi

exit 0
