#!/bin/sh
set -e

case "$1" in
    purge)
        if command -v systemctl >/dev/null 2>&1; then
            systemctl disable doggy.service || true
            systemctl disable doggy-lora.service || true
            systemctl disable mediamtx.service || true
            systemctl disable doggy-cleanup-media.timer || true
            systemctl daemon-reload || true
        fi
        ;;
    remove)
        if command -v systemctl >/dev/null 2>&1; then
            systemctl daemon-reload || true
        fi
        ;;
esac

exit 0
