# Included by CPack at package time so the DEB version matches this build.

if(NOT DEFINED DOGGY_VERSION_BASE OR DOGGY_VERSION_BASE STREQUAL "")
    set(DOGGY_VERSION_BASE "1.0.0")
endif()

get_filename_component(DOGGY_GIT_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
include("${CMAKE_CURRENT_LIST_DIR}/doggy-version.cmake")

set(CPACK_PACKAGE_VERSION "${DOGGY_VERSION}")
set(CPACK_DEBIAN_PACKAGE_VERSION "${DOGGY_VERSION}")
if(DEFINED CPACK_DEBIAN_PACKAGE_ARCHITECTURE AND NOT CPACK_DEBIAN_PACKAGE_ARCHITECTURE STREQUAL "")
    set(CPACK_DEBIAN_FILE_NAME
        "${CPACK_DEBIAN_PACKAGE_NAME}_${DOGGY_VERSION}_${CPACK_DEBIAN_PACKAGE_ARCHITECTURE}.deb")
endif()
